'use client';

import React, { useState, useTransition } from 'react';
import { saveLoveStory, deleteLoveStory } from '@/app/actions';
import { saveLoveStorySaas, deleteLoveStorySaas } from '@/app/actions-saas';
import { LoveStoryMilestone } from '@/lib/db';
import { Trash2, Plus, Sparkles, Heart, Calendar, Image as ImageIcon } from 'lucide-react';

interface LoveStoryFormProps {
  initialLoveStory: LoveStoryMilestone[];
  slug?: string;
}

export default function LoveStoryForm({ initialLoveStory, slug }: LoveStoryFormProps) {
  const [milestones, setMilestones] = useState<LoveStoryMilestone[]>(initialLoveStory);
  const [title, setTitle] = useState('');
  const [date, setDate] = useState('');
  const [description, setDescription] = useState('');
  const [photo, setPhoto] = useState('');
  
  const [isPending, startTransition] = useTransition();
  const [status, setStatus] = useState<{ success?: boolean; message?: string } | null>(null);
  const [uploading, setUploading] = useState(false);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    const formData = new FormData();
    formData.append('file', file);
    formData.append('type', 'images');

    try {
      const uploadUrl = slug ? `/api/upload?slug=${slug}` : '/api/upload';
      const res = await fetch(uploadUrl, {
        method: 'POST',
        body: formData,
      });
      const data = await res.json();
      if (data.success && data.url) {
        setPhoto(data.url);
      } else {
        alert(data.error || 'Upload failed');
      }
    } catch (err) {
      console.error(err);
      alert('Error uploading file');
    } finally {
      setUploading(false);
    }
  };

  const handleAdd = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim() || !description.trim()) return;
    setStatus(null);

    startTransition(async () => {
      try {
        const payload: LoveStoryMilestone = {
          id: '', // Will be generated by server
          title,
          date,
          description,
          photo
        };

        const res = slug 
          ? await saveLoveStorySaas(slug, payload)
          : await saveLoveStory(payload);

        if (res.success) {
          setStatus({ success: true, message: 'Milestone added successfully!' });
          setTitle('');
          setDate('');
          setDescription('');
          setPhoto('');
          window.location.reload();
        } else {
          setStatus({ success: false, message: 'Failed to add milestone.' });
        }
      } catch (err) {
        console.error(err);
        setStatus({ success: false, message: 'An error occurred.' });
      }
    });
  };

  const handleDelete = (id: string) => {
    if (!confirm('Are you sure you want to delete this milestone?')) return;
    setStatus(null);

    startTransition(async () => {
      try {
        const res = slug 
          ? await deleteLoveStorySaas(slug, id)
          : await deleteLoveStory(id);

        if (res.success) {
          setMilestones(prev => prev.filter(m => m.id !== id));
          setStatus({ success: true, message: 'Milestone deleted successfully.' });
        } else {
          setStatus({ success: false, message: 'Failed to delete milestone.' });
        }
      } catch (err) {
        console.error(err);
        setStatus({ success: false, message: 'Error deleting milestone.' });
      }
    });
  };

  return (
    <div className="space-y-6 font-outfit select-none">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 font-serif">Our Love Story</h1>
        <p className="text-gray-500 text-xs md:text-sm mt-1">Manage relationship milestones, dates, memories, and photos</p>
      </div>

      {status && (
        <div
          className={`p-3 rounded-xl text-sm font-semibold text-center border ${
            status.success
              ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
              : 'bg-red-50 text-red-800 border-red-200'
          }`}
        >
          {status.message}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Add Story Form */}
        <div className="lg:col-span-1">
          <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4 sticky top-6">
            <h3 className="text-sm font-bold text-[#800000] uppercase tracking-wider flex items-center space-x-2 pb-2 border-b border-gray-100">
              <Heart className="w-4 h-4 text-[#9B111E]" />
              <span>Add Milestone</span>
            </h3>

            <form onSubmit={handleAdd} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-gray-600 uppercase">Title *</label>
                <input
                  type="text"
                  required
                  value={title}
                  onChange={e => setTitle(e.target.value)}
                  placeholder="e.g. First Meet"
                  className="w-full mt-1 px-3.5 py-2.5 rounded-xl border border-gray-300 focus:outline-none focus:ring-1 focus:ring-[#800000] focus:border-[#800000] text-sm text-gray-800 bg-[#FDFBF7]"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-600 uppercase">Milestone Date / Period *</label>
                <input
                  type="text"
                  required
                  value={date}
                  onChange={e => setDate(e.target.value)}
                  placeholder="e.g. December 2024 or 12/12/2024"
                  className="w-full mt-1 px-3.5 py-2.5 rounded-xl border border-gray-300 focus:outline-none focus:ring-1 focus:ring-[#800000] focus:border-[#800000] text-sm text-gray-800 bg-[#FDFBF7]"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-600 uppercase">Description *</label>
                <textarea
                  required
                  value={description}
                  onChange={e => setDescription(e.target.value)}
                  placeholder="How you met, proposed, or a beautiful memory..."
                  rows={3}
                  className="w-full mt-1 px-3.5 py-2.5 rounded-xl border border-gray-300 focus:outline-none focus:ring-1 focus:ring-[#800000] focus:border-[#800000] text-sm text-gray-800 bg-[#FDFBF7] resize-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-600 uppercase">Upload Memory Image</label>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleFileUpload}
                  className="w-full mt-1 text-xs text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:text-xs file:font-semibold file:bg-amber-50 file:text-[#800000] hover:file:bg-amber-100 cursor-pointer"
                />
                {uploading && <span className="text-[10px] text-gray-400 animate-pulse block mt-1">Uploading image...</span>}
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-600 uppercase">Or Image URL</label>
                <input
                  type="url"
                  value={photo}
                  onChange={e => setPhoto(e.target.value)}
                  placeholder="https://images.unsplash.com/..."
                  className="w-full mt-1 px-3.5 py-2.5 rounded-xl border border-gray-300 focus:outline-none focus:ring-1 focus:ring-[#800000] focus:border-[#800000] text-sm text-gray-800 bg-[#FDFBF7]"
                />
              </div>

              <button
                type="submit"
                disabled={isPending}
                className="w-full bg-[#800000] hover:bg-[#9B111E] text-[#D4AF37] font-bold py-2.5 rounded-xl border border-[#D4AF37]/20 shadow flex items-center justify-center space-x-1.5 transition-colors cursor-pointer text-xs md:text-sm"
              >
                {isPending ? (
                  <span className="animate-spin h-5 w-5 border-2 border-[#D4AF37] border-t-transparent rounded-full"></span>
                ) : (
                  <>
                    <Plus className="w-4 h-4" />
                    <span>Add Milestone</span>
                  </>
                )}
              </button>
            </form>
          </div>
        </div>

        {/* Story List */}
        <div className="lg:col-span-2 space-y-4">
          {milestones.length === 0 ? (
            <div className="text-center py-16 bg-white rounded-2xl border border-gray-200 shadow-sm italic text-gray-500">
              No milestones added yet. Add your story details on the left.
            </div>
          ) : (
            <div className="relative border-l-2 border-[#D4AF37]/30 ml-4 space-y-8 py-4">
              {milestones.map(milestone => (
                <div key={milestone.id} className="relative pl-6">
                  {/* Dot */}
                  <span className="absolute -left-[9px] top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-[#800000] border-2 border-[#D4AF37]">
                    <Heart className="h-2 w-2 text-[#D4AF37] fill-[#D4AF37]" />
                  </span>

                  <div className="bg-white p-5 rounded-2xl border border-gray-200 shadow-sm space-y-3 flex flex-col md:flex-row md:space-x-4 md:space-y-0">
                    {milestone.photo && (
                      <div className="w-full md:w-32 h-32 rounded-xl overflow-hidden flex-shrink-0 border-2 border-[#D4AF37]/20">
                        <img src={milestone.photo} alt={milestone.title} className="w-full h-full object-cover" />
                      </div>
                    )}
                    
                    <div className="flex-1 flex flex-col justify-between">
                      <div>
                        <div className="flex items-center justify-between">
                          <h4 className="font-bold text-[#800000] font-serif text-lg">{milestone.title}</h4>
                          <button
                            onClick={() => handleDelete(milestone.id)}
                            disabled={isPending}
                            className="p-1.5 text-gray-400 hover:text-red-600 transition-colors cursor-pointer"
                            title="Delete Milestone"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                        <p className="text-[#9B111E] text-xs font-semibold flex items-center mt-1">
                          <Calendar className="w-3.5 h-3.5 mr-1" />
                          <span>{milestone.date}</span>
                        </p>
                        <p className="text-gray-600 text-sm mt-2 leading-relaxed">{milestone.description}</p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}